defaults:
  - dataset: atis_intent
  - model: attention
  - losses: vat
  - training: atis
  - misc: default
  - hydra: default
  - hydra/sweeper: range
  - hydra/launcher: ray
  - ray: default
  - wandb: default

rerank:
  part: 0.1