defaults:
  - hydra: default
  - hydra/sweeper: range
  - hydra/launcher: ray
  - ray: default
  - rerank: ce
misc:
  name: text
  id: ${id:}
  name: rerank
  device: 0
  test: False
  tqdm: False
  wandb: False