defaults:
  - dataset: imdb5000
  - model: lstm_1024
  - losses: vat
  - training: text
  - misc: default
  - hydra: default
  - hydra/sweeper: range
  - hydra/launcher: ray
  - ray: default
  - wandb: default