defaults:
  - dataset: atis
  - model: attention_tag
  - losses: vat
  - training: atis
  - misc: default
  - hydra: default
  - hydra/sweeper: range
  - hydra/launcher: ray
  - ray: default
  - wandb: default