losses:
  vat_old:
    class: viraal.losses.vat_loss_old.VAT
    params:
      device: 0
      eps: 5
      xi: 1e-5
      k: 1
  ce:
    class: torch.nn.CrossEntropyLoss
    params:
      reduction: none