training:
  iterator:
    class: datasets.unlabel_iterator.UnlabelIterator
    params:
      label_key: label
      labeled_part: 0.1
      label_min: 1
      batch_size: 64
  optimizer:
    class: torch.optim.Adam
    params:
      lr: 0.001
