dataset:
  reader:
    class: viraal.datasets.iob_intent.IobIntentDatasetReader
  splits:
    train: /u/home/badr/Corpus/atis/atis-2.train.w-intent.iob
    val: /u/home/badr/Corpus/atis/atis-2.dev.w-intent.iob
    test: /u/home/badr/Corpus/atis/atis.test.w-intent.iob
  embedding:
    vocab_namespace: tokens
    embedding_dim: 300
    pretrained_file: /u/home/badr/Corpus/atis/all_atis.wiki.en.ft.vec
  vocab:
    non_padded_namespaces: []