dataset:
  reader:
    class: viraal.datasets.imdb.ImdbDatasetReader
  splits:
    train: /u/home/badr/Expe/VirAAL/tests/fixtures/imdb/train
    val: /u/home/badr/Expe/VirAAL/tests/fixtures/imdb/val
    test: /u/home/badr/Expe/VirAAL/tests/fixtures/imdb/test
  embedding:
    vocab_namespace: tokens
    embedding_dim: 300
    pretrained_file: /u/home/badr/Corpus/aclImdb/imdb.wiki.en.vec
  