dataset:
  reader:
    class: viraal.datasets.imdb.ImdbDatasetReader
    params:
      max_length: 400
  splits:
    train: /u/home/badr/Corpus/aclImdb/train5000
    val: /u/home/badr/Corpus/aclImdb/val
    test: /u/home/badr/Corpus/aclImdb/test
  embedding:
    vocab_namespace: tokens
    embedding_dim: 300
    pretrained_file: /u/home/badr/Corpus/aclImdb/imdb.wiki.en.vec