dataset:
  reader:
    class: viraal.datasets.iob.IobDatasetReader
  splits:
    train: /u/home/badr/Corpus/snips/train.w-intent.iob
    val: /u/home/badr/Corpus/snips/valid.w-intent.iob
    test: /u/home/badr/Corpus/snips/test.w-intent.iob
  embedding:
    vocab_namespace: tokens
    embedding_dim: 300
    pretrained_file: /u/home/badr/Corpus/snips/snips.wiki.en.vec
  vocab:
    non_padded_namespaces: []